# Generated by Django 4.2.4 on 2023-09-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
