"""

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = Path.joinpath(BASE_DIR,'templates')
STATIC_DIR = Path.joinpath(BASE_DIR,'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-it*tmpcer8!bbhahn%oko_6fsb#)38v#m7^i93jcr(61*-fzln'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
 	

# test key
STRIPE_PUBLIC_KEY = 'pk_test_51NYBhaSCfPCuJGvgFUl9oj4vOagxAPXNTDnaYdxrqjiEdgBw40GfqpqIUDWinlvlvGn3YWdCGCyCwouPhhqMCpqB0052RVFJtO'
STRIPE_SECRET_KEY = 'sk_test_51NYBhaSCfPCuJGvgifF7TZwNUD8RnX2hm0nWiiFXhMEMJrK61GSgZcLq7pD69Ufk34iEFgmyT09iFlBfyaBqRzRd00IqNz7EXV'







# STRIPE_PUBLIC_KEY = 'pk_live_51NYBhaSCfPCuJGvgiOkHdJqMuXE4LazfeFhexGochVdetGmln9SqagLlKygwCYGpoz9zhpwg2J6pKH2bwSVB0dPG00GCrIY23L'
# STRIPE_SECRET_KEY = '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'




PAYPAL_TEST=True

paypal_receiver_email='sb-n2h5a26939454@business.example.com'

PAYPAL_CLIENT_ID = 'AcOuKi2HXx61K1JzjFWoAZgwO2yPs_lzxlXi_KyOuheoJoc5VhdLskfnLNVTpQ7xoXpSyKC6CE5-MB_Z'   
PAYPAL_SECRET_KEY = 'EK65Zbs-GUVoE_IiG_--CHhVOuGozCKjm194fX0tbpsNEqnbXVEe7gyMCaFIs9mKly3KUQAeRog2-sX6'
PAYPAL_MODE = 'sandbox'



ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'Business_setting',
    'Supports_faq',
    'ckeditor',  # ckeditor
    'ckeditor_uploader',
    'admin_app',
    
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
   
]

AUTH_USER_MODEL = 'login.GurujiUsers'
ROOT_URLCONF = 'guruspeaks.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'guruspeaks.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'mbdb/db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'
# MEDIA_URL='/img/'
# MEDIA_ROOT = '/media/'

MEDIA_URL='/img/'
MEDIA_ROOT = '/media/'

STATIC_URL = '/static/'


STATIC_DIR = BASE_DIR / 'static'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')


# STATICFILES_DIRS = [STATIC_DIR]
# MEDIA_ROOT=os.path.join(BASE_DIR,'static/assets/img')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# STATICFILES_DIRS = (
#   os.path.join(BASE_DIR,'static'),
#   )

STATICFILES_DIRS = [STATIC_DIR]

LOGIN_URL  = 'customer-login'
ASTROLOGER_LOGIN_URL = 'astrologer-login'
ADMIN_LOGIN_URL = 'admin-login'
# settings.py
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = '587'
# EMAIL_HOST_USER = 'care@gurujispeaks.com'  # Update this to the desired email address
# EMAIL_HOST_PASSWORD = 'ijczxttduzjnirur'
# EMAIL_USE_TLS = True


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'info@gurujispeaks.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'info@gurujispeaks.com'
EMAIL_HOST_PASSWORD = 'wxtlwrvkxszgoorj'
EMAIL_USE_TLS = True  # Use TLS for secure connection

# Secondary email configuration
EMAIL_BACKEND_CARE = 'django.core.mail.backends.smtp.EmailBackend'
CARE_FROM_EMAIL = 'care@gurujispeaks.com'
CARE_EMAIL_HOST = 'smtp.gmail.com'
CARE_EMAIL_PORT = 587
EMAIL_HOST_USER_CARE = 'care@gurujispeaks.com'
EMAIL_HOST_PASSWORD_CARE = 'ijczxttduzjnirur'
EMAIL_USE_TLS_CARE = True  # Use TLS for secure connection

# Third email configuration
EMAIL_BACKEND_CARE = 'django.core.mail.backends.smtp.EmailBackend'
CAREERS_FROM_EMAIL = 'careers@gurujispeaks.com'
CAREERS_EMAIL_HOST = 'smtp.gmail.com'
CAREERS_EMAIL_PORT = 587
EMAIL_HOST_USER_CAREERS = 'careers@gurujispeaks.com'
EMAIL_HOST_PASSWORD_CAREERS = 'utiqjtoqzbgvjexj'
EMAIL_USE_TLS_CAREERS = True  # Use TLS for secure connection



# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = '587'
# EMAIL_HOST_USER = 'zappkodesolutions@gmail.com'
# EMAIL_HOST_PASSWORD = 'jwfvyxtfpnapytpt'
# EMAIL_USE_TLS = True

CKEDITOR_UPLOAD_PATH = "uploads/"
CSRF_TRUSTED_ORIGINS = ['https://gurujispeaks.com', 'https://www.gurujispeaks.com']


