# Generated by Django 4.2.3 on 2023-07-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_to_astrologer_time',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='admin_to_customer_time',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='astrloger_to_admin_time',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='customer_to_admin_time',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
