# Generated by Django 4.2.4 on 2023-08-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_comment_admin_to_astrologer_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='plan_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan_purchase',
            name='plan_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='plan_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
