# Generated by Django 4.2.4 on 2023-08-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_comment_plan_id_plan_purchase_plan_id_wallet_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurujiusers',
            name='astro_approve_date',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='gurujiusers',
            name='astro_approve_time',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
