# Generated by Django 4.2.4 on 2023-09-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_gurujiusers_astro_approve_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gurujiusers',
            name='birth_place',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
