# Generated by Django 4.2.4 on 2023-09-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_admin_setting_plan_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurujiusers',
            name='astro_date',
            field=models.DateField(null=True),
        ),
    ]
