# Generated by Django 4.2.4 on 2023-09-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_gurujiusers_astro_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_purchase',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
    ]
