# Generated by Django 4.2.4 on 2023-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_comment_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment1',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment2',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
    ]
