# Generated by Django 4.2.6 on 2023-10-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_comment_comment1_alter_comment_comment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
