# Generated by Django 4.2.6 on 2023-10-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating1', models.CharField(blank=True, max_length=240, null=True)),
                ('comments', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
    ]
