# Generated by Django 4.2.6 on 2023-11-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurujiusers',
            name='review_comments1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gurujiusers',
            name='review_star1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
