# Generated by Django 4.2.6 on 2023-11-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_gurujiusers_review_comments1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gurujiusers',
            name='review_comments1',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
