# Generated by Django 4.2.6 on 2023-11-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_gurujiusers_review_comments1'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurujiusers',
            name='cust_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
