# Generated by Django 4.0.6 on 2023-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_gurujiusers_cust_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurujiusers',
            name='agora_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
