# Generated by Django 4.2.4 on 2023-09-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
